# Problem Set 4B
# Name: Lucas Harlien
# Collaborators:

import random


debug_mode = False

class Message(object):
    def __init__(self, input_text):
        '''
        Initializes a Message object

        input_text (string): the message's text

        a Message object has one attribute:
            the message text
        '''
        self.text = input_text

    def __repr__(self):
        '''
        Returns a human readable representation of the object
        DO NOT CHANGE

        Returns: (string) A representation of the object
        '''
        return f'''Message('{self.get_text()}')'''

    def get_text(self):
        '''
        Used to access the message text outside of the class

        Returns: (string) the message text
        '''
        return self.text

    def shift_char(self, char, shift):
        '''
        Used to shift a character as described in the pset handout

        char (string): the single character to shift.
                    ASCII value in the range: 32<=ord(char)<=126
        shift (int): the amount to shift char by

        Returns: (string) the shifted character with ASCII value in the range [32, 126]
        '''
        old_value = ord(char) #get ASCII value of char
        new_value = old_value -32 #get to range of 0 - 94
        new_value += shift #shift to new value
        new_value = (new_value%95) #mod to wrap around to range 0-94
        new_value += 32 #add back to get to new ASCII value
        new_char = chr(new_value)
        # if debug_mode: print(f"shifting {old_value},'{char}' by {shift}: shifted to {new_value}, {new_char}")
        return new_char


    def apply_pad(self, pad):
        '''
        Used to calculate the ciphertext produced by applying a one time pad to the message text.
        For each character in the text at index i shift that character by
            the amount specified by pad[i]

        pad (list of ints): a list of integers used to encrypt the message text
                        len(pad) == len(the message text)

        Returns: (string) The ciphertext produced using the one time pad
        '''
        old_text = self.text
        new_text = ""
        for i in range(len(old_text)):
            new_text += self.shift_char(old_text[i], pad[i])
        return new_text
 

class PlaintextMessage(Message):
    def __init__(self, input_text, input_pad=None):
        '''
        Initializes a PlaintextMessage object.

        input_text (string): the message's text
        pad (list of ints OR None): the pad to encrypt the input_text or None if left empty
            if pad is not None then len(pad) == len(self.input_text)

        A PlaintextMessage object inherits from Message. It has three attributes:
            the message text
            the pad (list of integers, determined by pad
                or generated randomly using self.generate_pad() if pad is None)
            the ciphertext (string, input_text encrypted using the pad)
        '''
        Message.__init__(self, input_text)
        if input_pad != None:
            self.pad = input_pad.copy()
        else:
            self.pad = self.generate_pad()

    def __repr__(self):
        '''
        Returns a human readable representation of the object
        DO NOT CHANGE

        Returns: (string) A representation of the object
        '''
        return f'''PlaintextMessage('{self.get_text()}', {self.get_pad()})'''

    def generate_pad(self):
        '''
        Generates a one time pad which can be used to encrypt the message text.

        The pad should be generated by making a new list and for each character
            in the message chosing a random number in the range [0, 110) and
            adding that number to the list.

        Returns: (list of integers) the new one time pad
        '''
        new_pad = []
        for char in self.text:
            new_pad.append(random.randint(0, 110))
        return new_pad

    def get_pad(self):
        '''
        Used to safely access your one time pad outside of the class

        Returns: (list of integers) a COPY of your pad
        '''
        return self.pad

    def get_ciphertext(self):
        '''
        Used to access the ciphertext produced by applying pad to the message text

        Returns: (string) the ciphertext
        '''
        return self.apply_pad(self.get_pad())

    def change_pad(self, new_pad):
        '''
        Changes the pad used to encrypt the message text and updates any other
        attributes that are determined by the pad.

        new_pad (list of ints): the new one time pad that should be associated with this message.
            len(new_pad) == len(the message text)

        Returns: nothing
        '''
        self.pad = new_pad
        if debug_mode:
            print("changing pad")
        self.apply_pad(self.get_pad())

class EncryptedMessage(Message):
    def __init__(self, input_text):
        '''
        Initializes an EncryptedMessage object

        input_text (string): the ciphertext of the message

        an EncryptedMessage object inherits from Message. It has one attribute:
            the message text (ciphertext)
        '''
        Message.__init__(self,input_text)

    def __repr__(self):
        '''
        Returns a human readable representation of the object
        DO NOT CHANGE

        Returns: (string) A representation of the object
        '''
        return f'''EncryptedMessage('{self.get_text()}')'''

    def decrypt_message(self, pad):
        '''
        Decrypts the message text that was encrypted with pad as described in the writeup

        pad (list of ints): the new one time pad used to encrypt the message.
            len(pad) == len(the message text)

        Returns: (PlaintextMessage) the decrypted message (containing the pad)
        '''
        old_text = self.get_text()
        if debug_mode:
            print("decrypting message")
            print(f"old text: {old_text}")
        new_text = ""
        for i in range(len(old_text)):
            new_text += self.shift_char(old_text[i],-pad[i])
        if debug_mode:
            print(f"New text: {new_text}")
        return PlaintextMessage(new_text, pad)

# if debug_mode:    
#     first_text = ""
#     sample_pad = []
#     for i in range(32,127):
#         first_text += chr(i)
#         sample_pad.append(1)
#     print("example text includes all valid characters")
#     print(first_text)

#     my_message = PlaintextMessage(first_text)

#     print(f"The plain message is {my_message.get_text()}")
#     print(f"The pad is {my_message.get_pad()}")
    
#     encrypted_message = EncryptedMessage(my_message.get_ciphertext())
    
#     print(f"The encrypted message is {encrypted_message.get_text()}")
    
#     decrypted_message = encrypted_message.decrypt_message(my_message.get_pad())
    
#     print(f"The decrypted message is {decrypted_message}")
    
    # second_text = ""
    # for char in first_text:
    #     second_text += my_message.shift_char(char, -32)